name: hdpgmm_music_experiment
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pip
  - scikit-learn==1.0.1
  - numpy==1.21.2
  - scipy==1.7.1
  - pandas==1.3.4
  - numba==0.55.1
  - pytorch==1.11.0
  - torchmetrics==0.8.1
  - librosa==0.9.1
  - tqdm==4.62.3
  - h5py==3.6.0
  - pip:
    - pytorch_lightning==0.8.5
    - soundfile==0.10.3.post1
    - -e git+https://github.com/eldrin/pytorch-hdpgmm@main#egg=hdpgmm
